# Generated by Django 5.2.1 on 2025-06-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_shoe_price_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=254),
        ),
    ]
