# Generated by Django 5.2.1 on 2025-06-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='category',
            field=models.CharField(choices=[('men', "Men's"), ('women', "Women's")], default='men', max_length=10),
        ),
    ]
